"""
Measured land-surface statistics from the actual pixels of a fetched scene.

Everything the report calls a percentage is computed here, from Sentinel-2
surface reflectance, using published spectral indices. Nothing on this path is
generated by a language model, and nothing is a placeholder: if the bands
needed for an index are absent the function says so and returns no number.

    NDVI  = (NIR - RED)   / (NIR + RED)        vegetation vigour
    MNDWI = (GREEN - SWIR) / (GREEN + SWIR)    open water        (Xu 2006)
    NDBI  = (SWIR - NIR)  / (SWIR + NIR)       built-up          (Zha 2003)
    BUI   = NDBI - NDVI                        built-up, vegetation-corrected

Class assignment is a decision cascade, not four independent masks, so the
percentages sum to 100 and a pixel is never counted as both water and built-up:

    water       MNDWI > 0.0
    vegetation  NDVI  >= 0.30                  (dense green cover)
    sparse veg  NDVI  in [0.18, 0.30)
    built-up    BUI   > 0.0  and NDVI < 0.18
    bare/other  everything else

The thresholds are the conventional ones from that literature. They are
scene-independent and stated in the report, so a reader can disagree with a
number by disagreeing with a threshold rather than by trusting the system.

Index ordering follows serve.aoi.S2_BANDS, which is also the order the trained
specialists consume.
"""
from __future__ import annotations

import os
from typing import Any

import numpy as np

# indices into serve.aoi.S2_BANDS
B_BLUE, B_GREEN, B_RED, B_NIR, B_SWIR16 = 1, 2, 3, 7, 10
GSD_M = 10.0                      # Sentinel-2 ground sample distance

CLASSES = ("water", "vegetation", "sparse vegetation", "built-up", "bare/other")


def _ratio(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """(a - b) / (a + b) with a zero denominator mapped to 0, not to inf."""
    num, den = a - b, a + b
    return np.divide(num, den, out=np.zeros_like(num), where=np.abs(den) > 1e-6)


def load_stack(path: str) -> np.ndarray | None:
    """The 12-band float cube written beside an AOI fetch, or None.

    `serve.aoi` writes <stem>.tif for display and <stem>.npz for the bands. A
    plain user upload has no sidecar, and RGB alone cannot produce NDVI, NDBI
    or MNDWI -- all three need NIR or SWIR. Returning None here is what makes
    the report say "not computable" instead of inventing a figure.
    """
    npz = os.path.splitext(path)[0] + ".npz"
    if not os.path.exists(npz):
        return None
    z = np.load(npz)
    if "s2" not in z:
        return None
    s2 = z["s2"].astype(np.float32)
    return s2 if s2.shape[0] >= 11 else None


def indices(s2: np.ndarray) -> dict[str, np.ndarray]:
    ndvi = _ratio(s2[B_NIR], s2[B_RED])
    mndwi = _ratio(s2[B_GREEN], s2[B_SWIR16])
    ndbi = _ratio(s2[B_SWIR16], s2[B_NIR])
    return {"ndvi": ndvi, "mndwi": mndwi, "ndbi": ndbi, "bui": ndbi - ndvi}


def classify(s2: np.ndarray) -> tuple[np.ndarray, np.ndarray, dict[str, np.ndarray]]:
    """Returns (class index per pixel, valid mask, the index rasters).

    A pixel with zero reflectance in every visible band is a fill pixel at the
    edge of a granule, not a dark surface. Counting those as "bare" would
    inflate the bare fraction of any AOI that touches a scene boundary.
    """
    ix = indices(s2)
    valid = (s2[[B_BLUE, B_GREEN, B_RED, B_NIR]].sum(0) > 0)

    cls = np.full(s2.shape[1:], CLASSES.index("bare/other"), np.int8)
    cls[ix["bui"] > 0.0] = CLASSES.index("built-up")
    cls[(ix["ndvi"] >= 0.18) & (ix["ndvi"] < 0.30)] = CLASSES.index("sparse vegetation")
    cls[ix["ndvi"] >= 0.30] = CLASSES.index("vegetation")
    cls[ix["mndwi"] > 0.0] = CLASSES.index("water")       # water wins outright
    return cls, valid, ix


def scene_stats(s2: np.ndarray) -> dict[str, Any]:
    """Per-class cover for one acquisition: percent of valid pixels and km²."""
    cls, valid, ix = classify(s2)
    n = int(valid.sum())
    if n == 0:
        return {"error": "every pixel is fill -- the AOI does not intersect "
                         "valid data in this scene"}
    px_km2 = (GSD_M ** 2) / 1e6

    cover = {}
    for i, name in enumerate(CLASSES):
        k = int(((cls == i) & valid).sum())
        cover[name] = {"pct": round(100.0 * k / n, 2),
                       "km2": round(k * px_km2, 3), "pixels": k}
    return {
        "valid_pixels": n,
        "area_km2": round(n * px_km2, 3),
        "cover": cover,
        "mean_ndvi": round(float(ix["ndvi"][valid].mean()), 4),
        "mean_mndwi": round(float(ix["mndwi"][valid].mean()), 4),
        "mean_ndbi": round(float(ix["ndbi"][valid].mean()), 4),
    }


def _delta(a: float, b: float) -> dict[str, float]:
    """Absolute change in percentage points and change relative to t1.

    Both, because they answer different questions. Built-up going 2% -> 3% of a
    scene is +1.0 pp, which sounds negligible, and +50% relative, which sounds
    dramatic. Reporting only one of them is how a true number misleads.
    """
    return {"delta_pp": round(b - a, 2),
            "relative_pct": round(100.0 * (b - a) / a, 1) if a > 1e-9 else None}


def change_stats(s2_a: np.ndarray, s2_b: np.ndarray) -> dict[str, Any]:
    """Bi-temporal comparison. `s2_a` is the earlier acquisition."""
    if s2_a.shape[1:] != s2_b.shape[1:]:
        h = min(s2_a.shape[1], s2_b.shape[1])
        w = min(s2_a.shape[2], s2_b.shape[2])
        s2_a, s2_b = s2_a[:, :h, :w], s2_b[:, :h, :w]

    ca, va, ia = classify(s2_a)
    cb, vb, ib = classify(s2_b)
    valid = va & vb
    n = int(valid.sum())
    if n == 0:
        return {"error": "the two acquisitions share no valid pixels"}
    px_km2 = (GSD_M ** 2) / 1e6

    out: dict[str, Any] = {"valid_pixels": n,
                           "area_km2": round(n * px_km2, 3),
                           "classes": {}}
    for i, name in enumerate(CLASSES):
        pa = 100.0 * int(((ca == i) & valid).sum()) / n
        pb = 100.0 * int(((cb == i) & valid).sum()) / n
        out["classes"][name] = {
            "t1_pct": round(pa, 2), "t2_pct": round(pb, 2),
            "t1_km2": round(pa / 100 * n * px_km2, 3),
            "t2_km2": round(pb / 100 * n * px_km2, 3),
            **_delta(pa, pb),
        }

    # dNDVI is the standard vegetation-change signal; |dNDVI| > 0.10 is the
    # threshold M5 was supervised on, so the two agree by construction.
    dndvi = (ib["ndvi"] - ia["ndvi"])[valid]
    out["vegetation_index_change"] = {
        "mean_dndvi": round(float(dndvi.mean()), 4),
        "gain_pct": round(100.0 * float((dndvi > 0.10).mean()), 2),
        "loss_pct": round(100.0 * float((dndvi < -0.10).mean()), 2),
        "changed_pct": round(100.0 * float((np.abs(dndvi) > 0.10).mean()), 2),
    }
    dmndwi = (ib["mndwi"] - ia["mndwi"])[valid]
    out["water_index_change"] = {
        "mean_dmndwi": round(float(dmndwi.mean()), 4),
        "gain_pct": round(100.0 * float((dmndwi > 0.10).mean()), 2),
        "loss_pct": round(100.0 * float((dmndwi < -0.10).mean()), 2),
    }
    transitioned = (ca != cb) & valid
    out["transitioned_pct"] = round(100.0 * int(transitioned.sum()) / n, 2)

    # what the newly built-up pixels used to be -- the question a planner asks
    new_built = (cb == CLASSES.index("built-up")) & \
                (ca != CLASSES.index("built-up")) & valid
    src = {}
    if int(new_built.sum()):
        for i, name in enumerate(CLASSES):
            k = int((new_built & (ca == i)).sum())
            if k:
                src[name] = round(100.0 * k / int(new_built.sum()), 1)
    out["new_built_up"] = {
        "km2": round(int(new_built.sum()) * px_km2, 3),
        "pct_of_scene": round(100.0 * int(new_built.sum()) / n, 2),
        "converted_from_pct": src,
    }
    return out


def analyse(images: list[dict[str, Any]]) -> dict[str, Any]:
    """Measured statistics for whatever imagery the run was given.

    Single image  -> per-class cover.
    Two optical   -> cover at both dates plus the change table.
    No band cube  -> `available: False` with the reason. Never a guess.
    """
    optical = [i for i in images if i.get("modality", "optical") != "sar"]
    stacks = [(i, load_stack(i["path"])) for i in optical]
    usable = [(i, s) for i, s in stacks if s is not None]

    if not usable:
        return {"available": False,
                "reason": "no 12-band cube beside the supplied image(s). NDVI, "
                          "NDBI and MNDWI need NIR and SWIR, which an RGB "
                          "upload does not carry -- fetch an AOI from the map "
                          "to get the full Sentinel-2 stack.",
                "gsd_m": GSD_M}

    out: dict[str, Any] = {"available": True, "gsd_m": GSD_M,
                           "method": "Sentinel-2 L2A surface reflectance; "
                                     "NDVI / MNDWI (Xu 2006) / NDBI (Zha 2003)",
                           "thresholds": {"water_mndwi": 0.0,
                                          "vegetation_ndvi": 0.30,
                                          "sparse_vegetation_ndvi": 0.18,
                                          "built_up_bui": 0.0,
                                          "change_dindex": 0.10}}
    if len(usable) == 1:
        img, s2 = usable[0]
        out["mode"] = "single"
        out["dates"] = [img.get("date")]
        out["scene"] = scene_stats(s2)
        return out

    # earlier date first; serve.aoi already inserts it that way, but a caller
    # can hand us anything, and comparing t2 against t1 backwards would flip
    # every sign in the report.
    pair = sorted(usable[:2], key=lambda x: x[0].get("date") or "")
    (ia_, sa), (ib_, sb) = pair
    out["mode"] = "bi-temporal"
    out["dates"] = [ia_.get("date"), ib_.get("date")]
    out["t1"] = scene_stats(sa)
    out["t2"] = scene_stats(sb)
    out["change"] = change_stats(sa, sb)
    return out


# --------------------------------------------------------------------------- #
# markdown
# --------------------------------------------------------------------------- #
def _row(cells) -> str:
    return "| " + " | ".join(str(c) for c in cells) + " |"


def to_markdown(a: dict[str, Any]) -> list[str]:
    """The measured-statistics section of the run report."""
    if not a.get("available"):
        return ["## Measured land cover", "",
                f"_Not computable: {a['reason']}_", ""]

    out = ["## Measured land cover", "",
           f"Computed from the pixels, not from a model. {a['method']}. "
           f"Ground sample distance {a['gsd_m']:.0f} m.", ""]

    if a["mode"] == "single":
        s = a["scene"]
        if "error" in s:
            return out + [f"_{s['error']}_", ""]
        out += [f"Acquisition **{a['dates'][0] or 'unknown date'}** · "
                f"{s['area_km2']} km² of valid pixels.", "",
                _row(["class", "cover %", "area km²"]),
                _row(["---", "---:", "---:"])]
        for name, v in s["cover"].items():
            out.append(_row([name, f"{v['pct']:.2f}%", f"{v['km2']:.3f}"]))
        out += ["", f"Mean NDVI **{s['mean_ndvi']:+.4f}** · "
                    f"mean MNDWI **{s['mean_mndwi']:+.4f}** · "
                    f"mean NDBI **{s['mean_ndbi']:+.4f}**.", ""]
        return out

    c = a["change"]
    if "error" in c:
        return out + [f"_{c['error']}_", ""]
    d1, d2 = a["dates"][0] or "t1", a["dates"][1] or "t2"
    out += [f"**{d1} → {d2}** · {c['area_km2']} km² compared.", "",
            _row(["class", f"{d1} %", f"{d2} %", "Δ pp", "Δ relative",
                  f"{d2} km²"]),
            _row(["---", "---:", "---:", "---:", "---:", "---:"])]
    for name, v in c["classes"].items():
        rel = "—" if v["relative_pct"] is None else f"{v['relative_pct']:+.1f}%"
        out.append(_row([name, f"{v['t1_pct']:.2f}%", f"{v['t2_pct']:.2f}%",
                         f"{v['delta_pp']:+.2f}", rel, f"{v['t2_km2']:.3f}"]))

    vg, wt, nb = (c["vegetation_index_change"], c["water_index_change"],
                  c["new_built_up"])
    out += ["",
            f"**Vegetation.** Mean ΔNDVI {vg['mean_dndvi']:+.4f}. "
            f"{vg['gain_pct']:.2f}% of the area gained vegetation "
            f"(ΔNDVI > +0.10) and {vg['loss_pct']:.2f}% lost it; "
            f"{vg['changed_pct']:.2f}% changed either way.",
            "",
            f"**Urbanisation.** Built-up cover moved from "
            f"{c['classes']['built-up']['t1_pct']:.2f}% to "
            f"{c['classes']['built-up']['t2_pct']:.2f}% of the area "
            f"({c['classes']['built-up']['delta_pp']:+.2f} pp). "
            f"{nb['km2']:.3f} km² became built-up that was not before "
            f"({nb['pct_of_scene']:.2f}% of the scene)"
            + (", converted from "
               + ", ".join(f"{k} {v:.1f}%"
                           for k, v in nb["converted_from_pct"].items())
               if nb["converted_from_pct"] else "") + ".",
            "",
            f"**Water.** Open water moved from "
            f"{c['classes']['water']['t1_pct']:.2f}% to "
            f"{c['classes']['water']['t2_pct']:.2f}% "
            f"({c['classes']['water']['delta_pp']:+.2f} pp). "
            f"Mean ΔMNDWI {wt['mean_dmndwi']:+.4f}; {wt['gain_pct']:.2f}% of "
            f"the area wetted and {wt['loss_pct']:.2f}% dried.",
            "",
            f"**{c['transitioned_pct']:.2f}%** of pixels changed class "
            f"between the two dates.", ""]
    return out


def dominant_class(a: dict[str, Any]) -> str | None:
    """The largest measured class, for cross-checking a generated description.

    Taken from the later acquisition in a bi-temporal run, because that is the
    image a scene description is generated from.
    """
    if not a.get("available"):
        return None
    scene = a.get("scene") or a.get("t2")
    cover = (scene or {}).get("cover")
    if not cover:
        return None
    return max(cover.items(), key=lambda kv: kv[1]["pct"])[0]


def headline(a: dict[str, Any]) -> list[dict[str, Any]]:
    """The three numbers the console shows as tiles. Empty when not measurable."""
    if not a.get("available"):
        return []
    if a["mode"] == "single":
        cv = a["scene"].get("cover", {})
        return [{"label": "VEGETATION", "value": f"{cv.get('vegetation', {}).get('pct', 0):.2f}%",
                 "note": f"{cv.get('vegetation', {}).get('km2', 0):.2f} km²"},
                {"label": "BUILT-UP", "value": f"{cv.get('built-up', {}).get('pct', 0):.2f}%",
                 "note": f"{cv.get('built-up', {}).get('km2', 0):.2f} km²"},
                {"label": "WATER", "value": f"{cv.get('water', {}).get('pct', 0):.2f}%",
                 "note": f"{cv.get('water', {}).get('km2', 0):.2f} km²"}]
    c = a["change"]["classes"]
    return [{"label": "VEGETATION", "value": f"{c['vegetation']['delta_pp']:+.2f} pp",
             "note": f"{c['vegetation']['t1_pct']:.2f}% → {c['vegetation']['t2_pct']:.2f}%"},
            {"label": "URBANISATION", "value": f"{c['built-up']['delta_pp']:+.2f} pp",
             "note": f"{a['change']['new_built_up']['km2']:.3f} km² newly built-up"},
            {"label": "WATER", "value": f"{c['water']['delta_pp']:+.2f} pp",
             "note": f"{c['water']['t1_pct']:.2f}% → {c['water']['t2_pct']:.2f}%"}]
